### PR TITLE
feat(app):Validations for Project Object

### PR DESCRIPTION
**Pull request by NehaChaudhary311**
**Added validations for project Object** 

1. If receives invalid project - throws 400
2. `@Valid` in controller : Better response(including the valid messages)

**Enhancements to be done:** `BindingResult` in controller

Screenshot 2022-06-17 at 1 21 24 AM

```json
    "message": "Validation failed for object='project'. Error count: 2",
    "errors": [
        {
            "codes": [
                "NotBlank.project.projectName",
                "NotBlank.projectName",
                "NotBlank.java.lang.String",
                "NotBlank"
            ],
            "arguments": [
                {
                    "codes": [
                        "project.projectName",
                        "projectName"
                    ],
                    "arguments": null,
                    "defaultMessage": "projectName",
                    "code": "projectName"
                }
            ],
            "defaultMessage": "Project name is required",
            "objectName": "project",
            "field": "projectName",
            "rejectedValue": "",
            "bindingFailure": false,
            "code": "NotBlank"
        },
        {
            "codes": [
                "Size.project.projectIdentifier",
                "Size.projectIdentifier",
                "Size.java.lang.String",
                "Size"
            ],
            "arguments": [
                {
                    "codes": [
                        "project.projectIdentifier",
                        "projectIdentifier"
                    ],
                    "arguments": null,
                    "defaultMessage": "projectIdentifier",
                    "code": "projectIdentifier"
                },
                5,
                4
            ],
            "defaultMessage": "Please use 4 to 5 characters",
            "objectName": "project",
            "field": "projectIdentifier",
            "rejectedValue": "4",
            "bindingFailure": false,
            "code": "Size"
        }
    ],
    "path": "/api/project"
```

### CODE REVIEW

**Review by cslite — APPROVED** [review]
Code changes look good. But, the sample output looks less readable. I think, putting that output in a code block would have been better, isn’t it?

**Comment by NehaChaudhary311** [comment]
@cslite The code block didn't help much and rather made it look clumsy.

**Comment by NehaChaudhary311** [comment]
@cslite  I tried using Errors and BindingRequest like below to customize the response of validation failed, but it asks me to use <Project> and doesn't let me use <String> 
Screenshot 2022-06-18 at 9 48 35 PM

**Comment by cslite** [comment]
since the return type is `ResponseEntity<Project>`, it will not accept an object of `ResponseEntity<String>`. We'll have to make an object of `ResponseEntity<Project>`, I think

**Comment by cslite** [comment]
@NehaChaudhary311 If you change the return type to `ResponseEntity<?>`, I think, your code can work.

**Comment by cslite** [comment]
> @cslite The code block didn't help much and rather made it look clumsy.

I edited it and moved it into a code block, does it look better now?

Before it was appearing as:
before

**Comment by NehaChaudhary311** [comment]
I tried with ? but it doesn't accept 😕 @cslite 

Screenshot 2022-06-18 at 10 58 10 PM

**Comment by cslite** [comment]
@NehaChaudhary311 change the return type of the function.. not at the place where you are returning

**Comment by cslite** [comment]
image

**Comment by NehaChaudhary311** [comment]
Woah.. worked like a charm! I understood now. Thanks!

Screenshot 2022-06-18 at 11 06 55 PM

**Pull request merged**
